services:

  plume:
    image: phlak/plume:${PLUME_VERSION:-latest}
    env_file: environment.d/plume.env
    ports:
      - ${PLUME_PORT:-8076}:80
    volumes:
      - ${PLUME_DATA_PATH:-./data}:/var/www/html/data
      - ${PLUME_CACHE_VOLUME:-plume-cache}:/var/www/html/cache
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  php:
    image: phlak/plume:${PLUME_VERSION:-latest}
    env_file: environment.d/plume.env
    volumes:
      - ${PLUME_DATA_PATH:-./data}:/var/www/html/data
      - ${PLUME_CACHE_VOLUME:-plume-cache}:/var/www/html/cache
      - /etc/localtime:/etc/localtime:ro
    profiles: [cli]
    entrypoint: php
    restart: never

  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

volumes:
  plume-cache: {}
